name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - released
  workflow_dispatch: {}

env:
  # Commands to create prebuilds using prebuildify
  NODE_BUILD_CMD: npx --no-install prebuildify --napi --strip --targets 18.0.0,20.0.0,22.0.0
  # Merge with NODE_BUILD_CMD when Node.js v18 is EOL
  NO_V18_NODE_BUILD_CMD: npx --no-install prebuildify --napi --strip --targets 20.0.0,22.0.0
  # Electron build command
  ELECTRON_BUILD_CMD: npx --no-install prebuildify --napi --strip --targets 26.0.0,27.0.0,28.0.0,29.0.0,30.0.0,31.0.0

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - macos-14
          - windows-2019
        node:
          - 18
          - 20
          - 22
    name: Testing Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: pip.exe install setuptools
      - if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install python-setuptools
      - if: ${{ !startsWith(matrix.os, 'windows') && !startsWith(matrix.os, 'macos') }}
        run: python3 -m pip install setuptools
      - run: npm install --ignore-scripts
      - run: npm run build-debug
      - run: npm test
      - name: Test SpatiaLite extension
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt update
          sudo apt install libsqlite3-mod-spatialite -y
          node -e "require('./lib/index.js')(':memory:').loadExtension('mod_spatialite').exec('SELECT InitSpatialMetaData();')"

  publish:
    if: ${{ github.event_name == 'release' }}
    name: Publishing to NPM
    runs-on: ubuntu-20.04
    needs:
      - prebuild
      - prebuild-alpine
      - prebuild-alpine-arm
      - prebuild-linux-arm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  prebuild:
    if: ${{ github.event_name == 'release' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - macos-14
          - windows-2019
    name: Prebuild on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: pip.exe install setuptools
      - if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install python-setuptools
      - if: ${{ !startsWith(matrix.os, 'windows') && !startsWith(matrix.os, 'macos') }}
        run: python3 -m pip install setuptools
      - run: npm install --ignore-scripts
      - run: ${{ env.NODE_BUILD_CMD }}
      - run: ${{ env.ELECTRON_BUILD_CMD }}
      - if: matrix.os == 'windows-2019'
        run: |
          ${{ env.NODE_BUILD_CMD }} --arch ia32
          ${{ env.NO_V18_NODE_BUILD_CMD }} --arch arm64
          ${{ env.ELECTRON_BUILD_CMD }} --arch ia32
          ${{ env.ELECTRON_BUILD_CMD }} --arch arm64

  prebuild-alpine:
    if: ${{ github.event_name == 'release' }}
    strategy:
      fail-fast: false
    name: Prebuild on alpine
    runs-on: ubuntu-latest
    container: node:18-alpine
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: apk add build-base git python3 py3-setuptools --update-cache
      - run: npm install --ignore-scripts
      - run: ${{ env.NODE_BUILD_CMD }}

  prebuild-alpine-arm:
    if: ${{ github.event_name == 'release' }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm/v7
          - arm64
    name: Prebuild on alpine (${{ matrix.arch }})
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run --rm -v $(pwd):/tmp/project --entrypoint /bin/sh --platform linux/${{ matrix.arch }} node:18-alpine -c "\
          apk add build-base git python3 py3-setuptools --update-cache && \
          cd /tmp/project && \
          npm install --ignore-scripts && \
          ${{ env.NODE_BUILD_CMD }}"

  prebuild-linux-arm:
    if: ${{ github.event_name == 'release' }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm/v7
          - arm64
    name: Prebuild on Linux (${{ matrix.arch }})
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run --rm -v $(pwd):/tmp/project --entrypoint /bin/sh --platform linux/${{ matrix.arch }} node:18 -c "\
          cd /tmp/project && \
          npm install --ignore-scripts && \
          ${{ env.NODE_BUILD_CMD }}"
